const bancoQuestoes = [
  {
    "id": 1,
    "enunciado": "Salvo disposição contrária, a lei começa a vigorar em todo o país quarenta e cinco dias depois de oficialmente publicada, sendo que, nos Estados estrangeiros, a obrigatoriedade da lei brasileira, quando admitida, se inicia três meses depois de publicada.",
    "gabarito": "Certo",
    "justificativa": "A questão reflete a literalidade do art. 1º da LINDB. O intervalo entre a publicação e a entrada em vigor é denominado vacatio legis. No Brasil, o prazo padrão é de 45 dias, caso a norma seja omissa. Para a eficácia extraterritorial em Estados estrangeiros, o legislador optou por um critério cronológico fixo de três meses, visando garantir tempo suficiente para o conhecimento da norma no exterior. É importante notar que este prazo se aplica apenas quando a lei brasileira é admitida em território estrangeiro por regras de Direito Internacional.",
    "lei": "Art. 1º Salvo disposição contrária, a lei começa a vigorar em todo o país quarenta e cinco dias depois de oficialmente publicada. § 1º A obrigatoriedade da lei brasileira, quando admitida em Estados estrangeiros, se inicia três meses depois de publicada.",
    "jurisprudencia": "O Superior Tribunal de Justiça (STJ) reafirma que o prazo de vacatio legis deve ser contado excluindo-se o dia do começo e incluindo o do vencimento, conforme a Lei Complementar 95/1998. No caso de normas de Direito Internacional, a aplicação da lei brasileira no exterior respeita a soberania local e tratados. A jurisprudência destaca que a vacatio legis é um postulado da segurança jurídica, impedindo a aplicação imediata de normas complexas sem o devido tempo para adaptação social e institucional."
  },
  {
    "id": 2,
    "enunciado": "Se, antes de entrar a lei em vigor, ocorrer nova publicação de seu texto, destinada a correção, o prazo de vacatio legis começará a correr da nova publicação apenas para as partes alteradas.",
    "gabarito": "Errado",
    "justificativa": "De acordo com o § 3º do art. 1º da LINDB, se houver nova publicação do texto legal destinada a correção antes da entrada em vigor (durante a vacatio legis), o prazo para a lei inteira começará a correr novamente da data da nova publicação. Não existe o fracionamento sugerido pela questão. A lógica é evitar que uma mesma lei tenha diferentes partes entrando em vigor em datas distintas, o que geraria insegurança jurídica e confusão hermenêutica para os aplicadores do direito.",
    "lei": "Art. 1º, § 3º Se, antes de entrar a lei em vigor, ocorrer nova publicação de seu texto, destinada a correção, o prazo deste artigo e dos parágrafos anteriores começará a correr da nova publicação.",
    "jurisprudencia": "A doutrina clássica e a jurisprudência administrativa seguem o entendimento de que a republicação por erro material durante a vacatio interrompe o prazo original. O STF já sinalizou que alterações substanciais em textos normativos pendentes de vigência exigem nova publicidade total para garantir o princípio da publicidade. A interpretação gramatical do §3º não deixa margem para a vigência fracionada, pois o 'prazo deste artigo' refere-se à norma como unidade orgânica e sistêmica."
  },
  {
    "id": 3,
    "enunciado": "No ordenamento jurídico brasileiro, admite-se o fenômeno da repristinação automática, de modo que, revogada a lei revogadora, a lei anterior recupera imediatamente sua vigência.",
    "gabarito": "Errado",
    "justificativa": "A LINDB veda expressamente a repristinação automática no seu art. 2º, § 3º. A repristinação ocorre quando uma lei revogada volta a valer porque a lei que a revogou foi, por sua vez, retirada do sistema. No Brasil, isso só acontece se a nova lei revogadora trouxer uma disposição expressa determinando o retorno da vigência da primeira lei. Sem essa cláusula expressa, a lei revogada permanece morta, evitando instabilidade no sistema normativo e garantindo que o legislador tenha clareza sobre quais normas estão ativas.",
    "lei": "Art. 2º, § 3º Salvo disposição em contrário, a lei revogada não se restaura por ter a lei revogadora perdido a vigência.",
    "jurisprudencia": "O Supremo Tribunal Federal, em sede de controle de constitucionalidade (ex: ADI 2.028), diferencia a repristinação (fenômeno legislativo) do efeito repristinatório indesejado (fenômeno judicial). Enquanto a repristinação legislativa exige previsão expressa, o efeito repristinatório decorrente de declaração de inconstitucionalidade opera ex tunc, fazendo com que a norma anterior volte a viger porque a norma revogadora nunca foi válida. Portanto, a regra do art. 2º, §3º da LINDB aplica-se ao processo legislativo ordinário, não se confundindo com o controle de constitucionalidade."
  },
  {
    "id": 4,
    "enunciado": "Quando a lei for omissa, o juiz decidirá o caso de acordo com a analogia, os costumes e os princípios gerais de direito, sendo-lhe vedado o uso da equidade como meio de integração.",
    "gabarito": "Errado",
    "justificativa": "Embora o art. 4º da LINDB mencione a analogia, costumes e princípios gerais de direito como meios de integração da norma em caso de lacuna, o ordenamento jurídico não veda o uso da equidade. Na verdade, o Código de Processo Civil e a própria doutrina admitem a equidade em situações específicas autorizadas por lei ou quando necessária para a aplicação da justiça no caso concreto. A questão está errada ao afirmar categoricamente que o uso da equidade é vedado como meio integrativo ou auxiliar.",
    "lei": "Art. 4º Quando a lei for omissa, o juiz decidirá o caso de acordo com a analogia, os costumes e os princípios gerais de direito.",
    "jurisprudencia": "O Superior Tribunal de Justiça admite o uso da equidade, especialmente em casos de fixação de honorários advocatícios ou em questões de Direito de Família e do Consumidor, onde a aplicação rígida da lei levaria a um absurdo jurídico. A jurisprudência entende que o art. 4º da LINDB não é um rol taxativo e exaustivo, mas sim uma ordem preferencial de integração. A equidade, embora não citada no caput, é um postulado decorrente da própria finalidade social da lei prevista no art. 5º da LINDB."
  },
  {
    "id": 5,
    "enunciado": "A lei em vigor terá efeito imediato e geral, respeitados o ato jurídico perfeito, o direito adquirido e a coisa julgada, conceitos estes definidos pela própria LINDB.",
    "gabarito": "Certo",
    "justificativa": "A LINDB estabelece o princípio da irretroatividade motivada no art. 6º. A lei nova aplica-se imediatamente aos processos em curso e fatos futuros, mas não pode atingir situações jurídicas já consolidadas. O ato jurídico perfeito é aquele já consumado segundo a lei vigente ao tempo em que se efetuou; o direito adquirido é aquele que já se incorporou ao patrimônio do titular; e a coisa julgada é a decisão judicial de que já não caiba recurso. Tais proteções são pilares da segurança jurídica constitucional.",
    "lei": "Art. 6º A Lei em vigor terá efeito imediato e geral, respeitados o ato jurídico perfeito, o direito adquirido e a coisa julgada. § 1º Reputa-se ato jurídico perfeito o já consumado segundo a lei vigente ao tempo em que se efetuou. § 2º Consideram-se adquiridos assim os direitos que o seu titular, ou alguém por ele, possa exercer, como aqueles cujo começo do exercício tenha termo pré-fixado, ou condição pré-estabelecida inalterável, a arbítrio de outrem. § 3º Chama-se coisa julgada ou caso julgado a decisão judicial de que já não caiba recurso.",
    "jurisprudencia": "O STF possui jurisprudência consolidada no sentido de que não existe direito adquirido a regime jurídico (ex: RE 596.701). Contudo, as situações já constituídas sob a égide da lei anterior devem ser respeitadas. Em matéria previdenciária, o princípio 'tempus regit actum' é a tradução prática do art. 6º da LINDB, garantindo que o benefício seja calculado com base na lei vigente ao tempo do preenchimento dos requisitos. A Corte Suprema entende que o art. 6º tem status de norma de sobredireito, vinculando tanto o legislador quanto o julgador."
  },
  {
    "id": 6,
    "enunciado": "Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão.",
    "gabarito": "Certo",
    "justificativa": "Este item aborda o 'consequencialismo jurídico' introduzido pela Lei nº 13.655/2018 (Art. 20 da LINDB). A norma exige que o julgador abandone o formalismo excessivo e a aplicação cega de princípios abstratos (como 'interesse público' ou 'moralidade') sem avaliar o impacto real da decisão na gestão pública e na sociedade. A motivação deve demonstrar que a decisão é viável e considerar os obstáculos enfrentados pelo gestor público, promovendo uma análise de custo-benefício social.",
    "lei": "Art. 20. Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão. Parágrafo único. A motivação demonstrará a necessidade e a adequação da medida imposta ou da invalidação de ato, contrato, ajuste, processo ou norma administrativa, inclusive em face das possíveis alternativas.",
    "jurisprudencia": "O Tribunal de Contas da União (TCU) e o STJ têm aplicado o Art. 20 para evitar decisões que paralisem a administração pública desnecessariamente. A jurisprudência destaca que a imposição de sanções ou a anulação de contratos deve ser precedida de análise sobre se a medida não causará mais dano ao erário do que a própria manutenção do ato irregular. O entendimento é que a LINDB agora impõe uma 'ética da responsabilidade' ao julgador, exigindo uma análise empírica e pragmática dos efeitos de suas ordens."
  },
  {
    "id": 7,
    "enunciado": "A decisão que decretar a invalidação de ato administrativo deverá indicar, de modo expresso, as consequências jurídicas e administrativas da detração, sendo desnecessário indicar condições para a regularização se houver má-fé do gestor.",
    "gabarito": "Errado",
    "justificativa": "O art. 21 da LINDB exige que a decisão de invalidação indique as consequências e, quando necessário, as condições para que a regularização ocorra de modo proporcional e equânime, sem prejuízo dos interesses gerais. A lei não faz exceção absoluta baseada na má-fé para a omissão dessas condições; o dever de transparência e indicação de consequências é um imperativo de segurança jurídica. Mesmo diante de irregularidades, a transição para a legalidade deve ser minimamente organizada pelo órgão julgador.",
    "lei": "Art. 21. A decisão que decretar a invalidação de ato, contrato, ajuste, processo ou norma administrativa deverá indicar de modo expresso as consequências jurídicas e administrativas da decisão. Parágrafo único. A decisão a que se refere o caput deste artigo deverá, quando for o caso, indicar as condições para que a nova regularização ocorra de modo proporcional e equânime e sem prejuízo aos interesses gerais, não se podendo impor aos sujeitos atingidos ônus ou perdas que, em função das peculiaridades do caso, sejam excessivos ou anormais.",
    "jurisprudencia": "A jurisprudência administrativa reforça que a anulação de concursos públicos ou licitações, por exemplo, deve observar o regime de transição do art. 21. O Poder Judiciário, ao anular atos, tem passado a modular os efeitos para garantir que a segurança jurídica prevaleça sobre a legalidade estrita quando a anulação imediata causar caos administrativo. O princípio da confiança legítima é frequentemente citado em conjunto com este artigo para proteger terceiros que agiram de boa-fé diante do ato agora invalidado."
  },
  {
    "id": 8,
    "enunciado": "O agente público responderá pessoalmente por suas decisões ou opiniões técnicas apenas em caso de dolo ou erro grosseiro.",
    "gabarito": "Certo",
    "justificativa": "Trata-se da responsabilidade subjetiva mitigada do agente público, prevista no art. 28 da LINDB. O objetivo é combater o 'apagão das canetas' ou o 'direito administrativo do medo', onde o gestor se recusa a decidir por medo de ser punido por erros interpretativos leves. Erro grosseiro é aquele manifesto, evidente e inescusável, praticado com culpa grave (negligência ou imprudência temerária). Se o erro for escusável ou fruto de uma interpretação razoável da lei, o agente não pode ser responsabilizado pessoalmente.",
    "lei": "Art. 28. O agente público responderá pessoalmente por suas decisões ou opiniões técnicas em caso de dolo ou erro grosseiro.",
    "jurisprudencia": "O STF, no julgamento do referendo na Medida Cautelar na ADI 6421, definiu que erro grosseiro é a 'falha grave, evidente, caracterizada pela ação ou omissão com elevado grau de negligência, imprudência ou imperícia'. O TCU também consolidou entendimento de que a responsabilização perante a Corte de Contas exige a caracterização dessa culpa grave. Essa barreira protetiva visa assegurar que o gestor proativo não seja penalizado por divergências doutrinárias ou pequenas falhas que não demonstrem desprezo pelo ordenamento."
  },
  {
    "id": 9,
    "enunciado": "As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "gabarito": "Certo",
    "justificativa": "O art. 17 da LINDB estabelece as 'cláusulas de reserva' ou 'limites de ordem pública' para a aplicação do direito estrangeiro no Brasil. Mesmo que as regras de conexão (como lex domicilii ou lex loci) indiquem a aplicação de uma lei externa, o juiz brasileiro deve afastá-la se o conteúdo for incompatível com os valores fundamentais do Estado Brasileiro, como a dignidade da pessoa humana, a paz social ou princípios democráticos básicos.",
    "lei": "Art. 17. As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil, quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "jurisprudencia": "O STJ, ao analisar pedidos de homologação de sentenças estrangeiras, aplica rigorosamente o art. 17. Um exemplo clássico é a negativa de homologação de sentenças que versem sobre guarda de menores ou divórcio que violem o contraditório ou princípios fundamentais da família brasileira. A jurisprudência define 'ordem pública' como um conceito jurídico indeterminado que deve ser preenchido pelos valores constitucionais vigentes, funcionando como uma válvula de segurança contra influências externas incompatíveis com a moralidade jurídica local."
  },
  {
    "id": 10,
    "enunciado": "A prova dos fatos ocorridos em país estrangeiro rege-se pela lei que nele vigorar, quanto ao ônus e aos meios de produzir-se, mas os tribunais brasileiros não admitem provas que a lei brasileira desconheça.",
    "gabarito": "Certo",
    "justificativa": "O art. 13 da LINDB separa a admissibilidade/produção da prova da sua validade instrumental. Enquanto a forma e o ônus seguem a lei do local do fato (lex loci), a aceitação desse meio de prova no processo depende da lei brasileira (lex fori). Se uma prova for obtida de forma que a lei brasileira considere ilícita ou desconheça por completo (ex: prova obtida mediante tortura ou métodos não previstos), ela não poderá ser utilizada no processo judicial nacional.",
    "lei": "Art. 13. A prova dos fatos ocorridos em país estrangeiro rege-se pela lei que nele vigorar, quanto ao ônus e aos meios de produzir-se, não admitindo os tribunais brasileiros provas que a lei brasileira desconheça.",
    "jurisprudencia": "A jurisprudência do STJ em casos de cooperação jurídica internacional destaca que o magistrado deve realizar um juízo de delibação. Se um documento estrangeiro segue as formalidades do país de origem, ele é aceito, desde que não confronte o sistema processual pátrio. O entendimento é que as regras de direito probatório têm natureza mista (material e processual), exigindo essa dupla verificação: a conformidade com o local de origem para a existência e a conformidade com a lex fori para a validade processual."
  },
  {
    "id": 11,
    "enunciado": "A qualificação e a regência das obrigações nascerão do lugar em que se constituírem, sendo que, se a obrigação for constituída no Brasil, o credor não poderá pleitear o cumprimento no estrangeiro se o devedor lá não possuir domicílio.",
    "gabarito": "Errado",
    "justificativa": "O art. 9º da LINDB estabelece que a qualificação e a regência das obrigações são determinadas pela lei do país em que se constituírem. Entretanto, a norma não veda que o credor busque o cumprimento de uma obrigação no estrangeiro. A possibilidade de execução depende das normas de Direito Internacional Privado e dos tratados de cooperação judiciária. A vedação absoluta alegada no enunciado não encontra respaldo no ordenamento jurídico pátrio.",
    "lei": "Art. 9º Para qualificar e reger as obrigações, aplicar-se-á a lei do país em que se constituírem.",
    "jurisprudencia": "O STJ entende que a autonomia da vontade pode, em certos contratos internacionais, eleger o foro e a lei aplicável. A jurisprudência destaca que a regra do art. 9º é o critério de conexão principal, mas não impede a soberania dos tribunais estrangeiros em reconhecer a competência para julgar obrigações constituídas no Brasil, desde que haja conexão suficiente e respeito ao devido processo legal internacional."
  },
  {
    "id": 12,
    "enunciado": "A sucessão por morte ou por ausência obedece à lei do país em que domiciliado o de cujus ou o desaparecido, qualquer que seja a natureza e a situação dos bens, exceto se a lei brasileira for mais benéfica ao cônjuge sobrevivente.",
    "gabarito": "Errado",
    "justificativa": "O art. 10 da LINDB determina que a sucessão por morte ou ausência obedece à lei do país em que domiciliado o falecido ou o desaparecido. A regra não admite a exceção de 'lei mais benéfica' mencionada. A única exceção prevista na lei está no §1º do mesmo artigo, que trata da sucessão de bens de estrangeiros situados no Brasil, garantindo aos filhos ou cônjuge brasileiro o direito de pleitear a sucessão em benefício da lei brasileira, caso esta lhes seja mais favorável.",
    "lei": "Art. 10. A sucessão por morte ou por ausência obedece à lei do país em que domiciliado o defunto ou o desaparecido, qualquer que seja a natureza e a situação dos bens.",
    "jurisprudencia": "A jurisprudência reforça a aplicação da lex domicilii para a sucessão universal, visando a unidade do inventário. O STF, em casos envolvendo sucessão de estrangeiros, tem aplicado o art. 10 com a ressalva do §1º, garantindo que o direito sucessório brasileiro proteja os nacionais, especialmente em casos de disparidade de regimes sucessórios entre o Brasil e o país de domicílio do falecido."
  },
  {
    "id": 13,
    "enunciado": "A adoção de pessoa maior de dezoito anos, mesmo que realizada no estrangeiro, não produz efeitos no Brasil se não houver homologação pelo Superior Tribunal de Justiça.",
    "gabarito": "Certo",
    "justificativa": "A adoção é regida pela lei do domicílio do adotante, conforme o art. 7º, § 5º da LINDB. Contudo, para que qualquer sentença estrangeira produza efeitos no território nacional, é indispensável a homologação pelo STJ. A adoção, por envolver o estado da pessoa, exige controle rigoroso de legalidade e verificação da inexistência de ofensa à ordem pública, atendendo ao princípio da segurança jurídica e da proteção ao menor/adotado.",
    "lei": "Art. 7º, § 5º O reconhecimento de filho adotivo, para fins de adoção, será regido pela lei do domicílio do adotante.",
    "jurisprudencia": "O STJ tem entendimento consolidado de que a sentença estrangeira de adoção não é autoejecutável. A jurisprudência destaca que a soberania nacional exige a conferência da sentença estrangeira antes que ela altere o registro civil ou produza efeitos sucessórios/familiares no Brasil. A decisão deve observar se o processo original respeitou o contraditório e se não há violação à moralidade local."
  },
  {
    "id": 14,
    "enunciado": "Na aplicação da lei, o juiz atenderá aos fins sociais a que ela se dirige e às exigências do bem comum, sendo esta uma diretriz de interpretação teleológica.",
    "gabarito": "Certo",
    "justificativa": "O art. 5º da LINDB estabelece o método de interpretação teleológica (finalística). O magistrado, ao aplicar a norma, não deve se limitar à exegese literal ou gramatical, mas buscar o objetivo social da lei. Essa diretriz impede que o formalismo jurídico se torne um obstáculo à realização da justiça, garantindo que o Direito cumpra sua função de pacificação social e busca pelo bem comum.",
    "lei": "Art. 5º Na aplicação da lei, o juiz atenderá aos fins sociais a que ela se dirige e às exigências do bem comum.",
    "jurisprudencia": "O STJ utiliza frequentemente o art. 5º para justificar interpretações que visam proteger a dignidade da pessoa humana em detrimento de uma leitura fria da lei, especialmente no Direito do Consumidor e no Direito de Família. A jurisprudência entende que este dispositivo é uma cláusula de abertura que confere ao juiz poder interpretativo para adequar a norma abstrata às mutações da realidade social."
  },
  {
    "id": 15,
    "enunciado": "A autoridade pública, ao invalidar ato administrativo, deve adotar regime de transição quando necessário, o qual pode incluir a fixação de regime de compensação financeira, se for o caso.",
    "gabarito": "Certo",
    "justificativa": "A Lei 13.655/2018 incluiu o art. 22 na LINDB, prevendo que a invalidação de atos não deve ser um processo abrupto que cause danos desproporcionais. O regime de transição serve para mitigar o impacto da anulação, permitindo que a administração pública e os administrados se ajustem à nova realidade jurídica sem perdas excessivas. A compensação financeira é um dos instrumentos possíveis para equilibrar o prejuízo causado pelo desfazimento do ato.",
    "lei": "Art. 22. Na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor e as exigências das políticas públicas a seu cargo, sem prejuízo dos direitos dos administrados.",
    "jurisprudencia": "A jurisprudência tem aplicado o art. 22 como um escudo contra o ativismo judicial desmedido em políticas públicas. O entendimento é de que o magistrado não pode ignorar as limitações orçamentárias e as dificuldades logísticas enfrentadas pelo gestor público ao exigir o cumprimento de uma prestação. A decisão judicial deve ser técnica e considerar o impacto sistêmico da medida sobre os recursos públicos."
  },
  {
    "id": 16,
    "enunciado": "O Direito Brasileiro adota o princípio da territorialidade moderada, permitindo que, em certas hipóteses, a lei pessoal (domicílio) prevaleça sobre a lei do local do ato.",
    "gabarito": "Certo",
    "justificativa": "A LINDB segue a tradição de que a pessoa é regida pela lei do seu domicílio (lei pessoal), conforme art. 7º. Por outro lado, para atos como contratos ou crimes, aplica-se a lei do local (lex loci). Essa coexistência entre lei pessoal e lei territorial define o sistema brasileiro como territorialidade moderada ou temperada, buscando harmonizar a segurança jurídica nas relações sociais com a autonomia individual.",
    "lei": "Art. 7º A lei do país em que domiciliada a pessoa determina as regras sobre o começo e o fim da personalidade, o nome, a capacidade e os direitos de família.",
    "jurisprudencia": "A jurisprudência internacionalista brasileira, amparada pela LINDB, defende a aplicação da lex domicilii para garantir que o indivíduo carregue consigo seu status jurídico. O STJ reforça que essa escolha legislativa evita que a capacidade de uma pessoa mude conforme o local onde ela viaja, preservando a coerência das relações jurídicas pessoais."
  },
  {
    "id": 17,
    "enunciado": "A revisão de atos, contratos, ajustes, processos ou normas administrativas, se for de natureza preparatória, dispensa a fundamentação quanto ao impacto das consequências práticas.",
    "gabarito": "Errado",
    "justificativa": "A Lei 13.655/2018, ao alterar a LINDB, não criou exceções quanto à necessidade de análise consequencialista para atos preparatórios. O art. 20 aplica-se a todas as esferas (administrativa, controladora e judicial) e não distingue a fase do processo administrativo. A fundamentação sobre as consequências é um requisito de validade para a motivação de qualquer decisão que envolva o poder público.",
    "lei": "Art. 20. Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão.",
    "jurisprudencia": "A jurisprudência do TCU é clara: a motivação é elemento essencial do ato administrativo e, sob a égide da nova LINDB, deve ser robusta. Decisões que ignoram as consequências práticas, mesmo em fases intermediárias, podem ser anuladas por vício de motivação, pois a falta de análise consequencialista compromete a própria legalidade do procedimento."
  },
  {
    "id": 18,
    "enunciado": "A pessoa jurídica estrangeira é regida pela lei do país onde foi constituída, mas, para funcionar no Brasil, deve submeter-se às leis brasileiras, incluindo a exigência de autorização do Poder Executivo.",
    "gabarito": "Certo",
    "justificativa": "O art. 11 da LINDB estabelece que as organizações destinadas a fins de interesse coletivo, como as sociedades e fundações, obedecem à lei do país em que forem constituídas. Contudo, o §2º deixa claro que as pessoas jurídicas estrangeiras, para funcionarem no território nacional, precisam de autorização do governo brasileiro, submetendo-se às leis pátrias no que tange ao seu funcionamento e atividades locais.",
    "lei": "Art. 11. As organizações destinadas a fins de interesse coletivo, como as sociedades e as fundações, obedecem à lei do Estado em que se constituírem.",
    "jurisprudencia": "A jurisprudência pátria, em sintonia com o art. 11, diferencia a existência jurídica (reconhecida pela lei de origem) da capacidade operacional (regulada pela lei do local de atuação). O STJ entende que a pessoa jurídica estrangeira que atua no Brasil sem autorização não pode invocar imunidades processuais, devendo responder pelas obrigações contraídas no país como se entidade local fosse."
  },
  {
    "id": 19,
    "enunciado": "A interpretação de normas administrativas deve considerar as circunstâncias práticas que limitaram a ação do gestor, desde que o prejuízo aos direitos dos administrados seja mínimo.",
    "gabarito": "Certo",
    "justificativa": "O art. 22 da LINDB é explícito ao determinar que a interpretação de normas de gestão deve levar em conta os obstáculos e dificuldades reais do gestor. Isso visa proteger o gestor público de punições baseadas em ideais de perfeição inalcançáveis, garantindo que a análise seja feita dentro do contexto fático, sem perder de vista que os direitos dos administrados devem ser protegidos dentro do possível e do razoável.",
    "lei": "Art. 22. Na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor e as exigências das políticas públicas a seu cargo, sem prejuízo dos direitos dos administrados.",
    "jurisprudencia": "A jurisprudência recente, especialmente em tribunais de contas, tem absolvido gestores que, mesmo falhando em metas, demonstraram ter agido com base em alternativas viáveis diante de restrições orçamentárias severas. O entendimento é que o 'bom administrador' não é o que nunca falha, mas o que toma decisões fundamentadas e coerentes com a realidade fática enfrentada."
  },
  {
    "id": 20,
    "enunciado": "Considera-se que uma lei estrangeira ofende a ordem pública quando, embora sendo legal em seu país de origem, contraria a estrutura constitucional brasileira, como no caso de leis que discriminem pessoas em razão de religião ou etnia.",
    "gabarito": "Certo",
    "justificativa": "O conceito de ordem pública na LINDB (Art. 17) é um conceito jurídico indeterminado, mas que possui núcleo duro na Constituição Federal de 1988. Leis estrangeiras que permitam a discriminação ferem o princípio da igualdade e da dignidade da pessoa humana, pilares do nosso ordenamento. Assim, o STJ e o STF rejeitam categoricamente qualquer norma ou sentença que viole esses princípios fundamentais, independentemente de ser válida onde foi criada.",
    "lei": "Art. 17. As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil, quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "jurisprudencia": "A jurisprudência consolidou que a ordem pública não é apenas o conjunto de normas cogentes, mas o conjunto de valores supremos da sociedade brasileira. O STJ, ao negar a homologação de sentenças estrangeiras, frequentemente cita a ofensa à ordem pública quando a decisão viola o devido processo legal ou preceitos fundamentais da nossa Carta Magna."
  },
  {
    "id": 18,
    "enunciado": "A pessoa jurídica estrangeira é regida pela lei do país onde foi constituída, mas, para funcionar no Brasil, deve submeter-se às leis brasileiras, incluindo a exigência de autorização do Poder Executivo.",
    "gabarito": "Certo",
    "justificativa": "O art. 11 da LINDB estabelece que as organizações destinadas a fins de interesse coletivo, como as sociedades e fundações, obedecem à lei do país em que forem constituídas. Contudo, o §2º deixa claro que as pessoas jurídicas estrangeiras, para funcionarem no território nacional, precisam de autorização do governo brasileiro, submetendo-se às leis pátrias no que tange ao seu funcionamento e atividades locais.",
    "lei": "Art. 11. As organizações destinadas a fins de interesse coletivo, como as sociedades e as fundações, obedecem à lei do Estado em que se constituírem.",
    "jurisprudencia": "A jurisprudência pátria, em sintonia com o art. 11, diferencia a existência jurídica (reconhecida pela lei de origem) da capacidade operacional (regulada pela lei do local de atuação). O STJ entende que a pessoa jurídica estrangeira que atua no Brasil sem autorização não pode invocar imunidades processuais, devendo responder pelas obrigações contraídas no país como se entidade local fosse."
  },
  {
    "id": 19,
    "enunciado": "A interpretação de normas administrativas deve considerar as circunstâncias práticas que limitaram a ação do gestor, desde que o prejuízo aos direitos dos administrados seja mínimo.",
    "gabarito": "Certo",
    "justificativa": "O art. 22 da LINDB é explícito ao determinar que a interpretação de normas de gestão deve levar em conta os obstáculos e dificuldades reais do gestor. Isso visa proteger o gestor público de punições baseadas em ideais de perfeição inalcançáveis, garantindo que a análise seja feita dentro do contexto fático, sem perder de vista que os direitos dos administrados devem ser protegidos dentro do possível e do razoável.",
    "lei": "Art. 22. Na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor e as exigências das políticas públicas a seu cargo, sem prejuízo dos direitos dos administrados.",
    "jurisprudencia": "A jurisprudência recente, especialmente em tribunais de contas, tem absolvido gestores que, mesmo falhando em metas, demonstraram ter agido com base em alternativas viáveis diante de restrições orçamentárias severas. O entendimento é que o 'bom administrador' não é o que nunca falha, mas o que toma decisões fundamentadas e coerentes com a realidade fática enfrentada."
  },
  {
    "id": 20,
    "enunciado": "Considera-se que uma lei estrangeira ofende a ordem pública quando, embora sendo legal em seu país de origem, contraria a estrutura constitucional brasileira, como no caso de leis que discriminem pessoas em razão de religião ou etnia.",
    "gabarito": "Certo",
    "justificativa": "O conceito de ordem pública na LINDB (Art. 17) é um conceito jurídico indeterminado, mas que possui núcleo duro na Constituição Federal de 1988. Leis estrangeiras que permitam a discriminação ferem o princípio da igualdade e da dignidade da pessoa humana, pilares do nosso ordenamento. Assim, o STJ e o STF rejeitam categoricamente qualquer norma ou sentença que viole esses princípios fundamentais, independentemente de ser válida onde foi criada.",
    "lei": "Art. 17. As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil, quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "jurisprudencia": "A jurisprudência consolidou que a ordem pública não é apenas o conjunto de normas cogentes, mas o conjunto de valores supremos da sociedade brasileira. O STJ, ao negar a homologação de sentenças estrangeiras, frequentemente cita a ofensa à ordem pública quando a decisão viola o devido processo legal ou preceitos fundamentais da nossa Carta Magna."
  },
  {
    "id": 21,
    "enunciado": "A vedação à repristinação automática prevista na LINDB não impede que o legislador, ao editar uma nova lei que revoga uma lei revogadora, declare expressamente que a lei original voltará a vigorar.",
    "gabarito": "Certo",
    "justificativa": "O § 3º do art. 2º da LINDB estabelece que a lei revogada não se restaura por ter a lei revogadora perdido a vigência, salvo disposição em contrário. Portanto, o legislador possui plena autonomia para utilizar a técnica da repristinação expressa. O que o sistema jurídico veda é a repristinação tácita, que causaria grave insegurança jurídica, pois o cidadão não saberia quais normas estão em vigor apenas pela análise da revogação de uma lei posterior.",
    "lei": "Art. 2º, § 3º Salvo disposição em contrário, a lei revogada não se restaura por ter a lei revogadora perdido a vigência.",
    "jurisprudencia": "O Supremo Tribunal Federal, ao distinguir a repristinação da restauração de eficácia, esclarece que a vontade do legislador é o fator decisivo. Em diversas ações de controle concentrado, o STF tem validado dispositivos legais que expressamente dispõem sobre a volta de vigência de normas anteriores, desde que tal intenção seja clara, evitando que o aplicador do direito presuma a vigência de normas que se encontravam superadas ou revogadas pelo ordenamento.",
  },
  {
    "id": 22,
    "enunciado": "Para fins de segurança jurídica, a autoridade pública pode celebrar compromisso com os interessados para eliminar irregularidade ou incerteza jurídica, cujo compromisso produzirá efeitos vinculantes após a aprovação da autoridade hierarquicamente superior.",
    "gabarito": "Certo",
    "justificativa": "O art. 26 da LINDB introduziu o compromisso (acordo administrativo) como um instrumento de governança e solução consensual. O parágrafo único deste artigo estabelece que tal compromisso somente produzirá efeitos após a oitiva do órgão de controle e após a sua devida publicidade, visando a transparência. A aprovação ou a submissão aos órgãos de controle (como o Ministério Público ou Tribunais de Contas) é medida essencial para evitar que acordos escondam irregularidades.",
    "lei": "Art. 26. Para eliminar irregularidade, incerteza jurídica ou situação contenciosa na aplicação do direito público, inclusive no caso de expedição de licença, a autoridade administrativa poderá, após oitiva do órgão jurídico e, quando for o caso, após realização de consulta pública, e presentes razões de relevante interesse geral, celebrar compromisso com os interessados.",
    "jurisprudencia": "O Tribunal de Contas da União tem incentivado o uso dos mecanismos de consenso da LINDB, entendendo que a administração pública deve buscar resultados efetivos e não apenas a punição. A jurisprudência destaca que o compromisso previsto no art. 26 não é uma 'carta branca' para perdoar ilícitos, mas um meio de sanear situações complexas onde a aplicação rígida da lei traria mais prejuízo social do que a solução negociada e transparente.",
  },
  {
    "id": 23,
    "enunciado": "Na aplicação da lei, o juiz deve decidir com base em valores jurídicos abstratos, priorizando a moralidade e o interesse público sobre os dados concretos do caso, quando a norma for omissa.",
    "gabarito": "Errado",
    "justificativa": "O art. 20 da LINDB, inserido pela Lei 13.655/2018, veda expressamente a decisão baseada apenas em valores jurídicos abstratos sem a devida análise das consequências práticas. O magistrado tem o dever de fundamentar a decisão com base em dados empíricos e na análise das alternativas viáveis. A moralidade e o interesse público são princípios norteadores, mas não podem ser utilizados como conceitos 'vazios' que dispensem o julgador do dever de avaliar o impacto real de sua decisão na vida do administrado ou no orçamento público.",
    "lei": "Art. 20. Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão.",
    "jurisprudencia": "A jurisprudência do STJ tem sido rigorosa quanto ao dever de fundamentação analítica. O tribunal entende que, após a reforma da LINDB, o 'consequencialismo' tornou-se uma obrigação processual. Decisões que se limitam a invocar princípios genéricos sem demonstrar por que aquela solução é a menos gravosa ou a mais eficiente perante a realidade fática são frequentemente cassadas por ausência de fundamentação adequada.",
  },
  {
    "id": 24,
    "enunciado": "A LINDB dispõe que, quando uma autoridade administrativa for decidir sobre a validade de um ato que tenha gerado direitos, deverá considerar as consequências jurídicas da decisão, mas não as consequências administrativas.",
    "gabarito": "Errado",
    "justificativa": "O art. 21 da LINDB é explícito ao determinar que a autoridade administrativa deve indicar de modo expresso as consequências tanto **jurídicas** quanto **administrativas** da decisão de invalidação. A intenção do legislador é garantir que o gestor público não anule atos de maneira leviana, ciente de que tal decisão pode paralisar serviços públicos, gerar novos contratos emergenciais ou criar passivos indenizatórios para o Estado.",
    "lei": "Art. 21. A decisão que decretar a invalidação de ato, contrato, ajuste, processo ou norma administrativa deverá indicar de modo expresso as consequências jurídicas e administrativas da decisão.",
    "jurisprudencia": "O entendimento consolidado é que a invalidação administrativa está sujeita a um controle de proporcionalidade mais rigoroso do que era antes de 2018. A jurisprudência, tanto judicial quanto dos órgãos de controle, exige que a autoridade que anula um ato demonstre, em seu relatório, como o vácuo deixado pela anulação será preenchido, garantindo que o interesse público continue sendo atendido sem hiatos prejudiciais aos usuários dos serviços.",
  },
  {
    "id": 25,
    "enunciado": "A capacidade da pessoa para exercer direitos é regida pela lei do local onde o ato for praticado, independentemente de onde a pessoa tenha seu domicílio.",
    "gabarito": "Errado",
    "justificativa": "Pelo art. 7º da LINDB, a capacidade da pessoa é regida pela lei do país em que ela é domiciliada. O Direito Brasileiro adota a 'lei pessoal' como regra para a capacidade civil. Mesmo que o indivíduo pratique um ato em país estrangeiro, sua capacidade para tal prática é aferida, em regra, por sua lei pessoal (domicílio), garantindo a proteção da própria pessoa contra atos que ela não poderia praticar segundo a lei que rege sua existência jurídica.",
    "lei": "Art. 7º A lei do país em que domiciliada a pessoa determina as regras sobre o começo e o fim da personalidade, o nome, a capacidade e os direitos de família.",
    "jurisprudencia": "A jurisprudência sobre o tema esclarece que a aplicação da lei pessoal visa à uniformidade da capacidade. Se a capacidade mudasse a cada fronteira que o indivíduo cruzasse, a segurança das relações jurídicas internacionais estaria comprometida. O STJ reforça que a lex domicilii funciona como um estatuto pessoal que acompanha o sujeito, salvo em hipóteses excepcionais onde o interesse público local (lex loci) se sobrepõe por força de leis de aplicação imediata.",
  },
  {
    "id": 26,
    "enunciado": "A LINDB estabelece que o parecer técnico utilizado como base para a tomada de decisão administrativa não vincula o gestor, mas, se este o seguir, o parecer passa a ser o único responsável por eventuais irregularidades.",
    "gabarito": "Errado",
    "justificativa": "O art. 28 da LINDB estabelece a responsabilidade pessoal do agente público em caso de dolo ou erro grosseiro. A existência de um parecer técnico não transfere automaticamente a responsabilidade. Se o gestor, agindo com erro grosseiro ou dolo, decide em desacordo com o parecer ou o utiliza como escudo para decisões manifestamente ilegais, ele responde pessoalmente. O parecer é um instrumento de suporte, não um instrumento de blindagem contra a responsabilização do tomador de decisão final.",
    "lei": "Art. 28. O agente público responderá pessoalmente por suas decisões ou opiniões técnicas em caso de dolo ou erro grosseiro.",
    "jurisprudencia": "Os Tribunais de Contas têm entendimento firme de que o parecer jurídico ou técnico é uma peça de suporte, não de submissão. O gestor tem o dever de avaliar criticamente a opinião técnica. Se o gestor percebe ou deveria perceber que a decisão é manifestamente contrária à lei ou ao interesse público, não pode se eximir alegando que 'seguiu o parecer'. A responsabilidade do agente público decorre da sua decisão final e da ciência das implicações dessa decisão.",
  },
  {
    "id": 27,
    "enunciado": "Nas esferas administrativa, controladora e judicial, a decisão que impõe nova interpretação ou orientação sobre norma de conteúdo indeterminado deve prever regime de transição.",
    "gabarito": "Certo",
    "justificativa": "O art. 23 da LINDB determina que a mudança de orientação de uma autoridade, em caso de norma de conteúdo indeterminado, deve ser acompanhada de regime de transição, caso seja necessário para preservar a segurança jurídica. Essa norma evita o 'choque' provocado por mudanças bruscas de interpretação (ex: uma mudança de jurisprudência do TCU ou de entendimento de uma agência reguladora) que prejudicariam quem organizou sua conduta com base na interpretação anterior.",
    "lei": "Art. 23. A decisão administrativa, controladora ou judicial que estabelecer interpretação ou orientação nova sobre norma de conteúdo indeterminado, impondo novo dever ou novo condicionamento de direito, deverá prever regime de transição quando indispensável para que o novo dever ou condicionamento de direito seja cumprido de modo proporcional, equânime e eficiente e sem prejuízo aos interesses gerais.",
    "jurisprudencia": "A jurisprudência brasileira tem evoluído para reconhecer que o princípio da proteção à confiança legítima é o fundamento do art. 23. Os tribunais têm exigido que as mudanças de orientação, especialmente em matérias tributárias e regulatórias, respeitem a anterioridade mínima ou concedam prazos de adequação, sob pena de a nova interpretação ser declarada ineficaz para situações que se consolidaram sob a vigência do entendimento anterior.",
  },
  {
    "id": 28,
    "enunciado": "A LINDB prevê que a consulta pública é obrigatória para a celebração de qualquer compromisso administrativo, sob pena de nulidade absoluta do ato.",
    "gabarito": "Errado",
    "justificativa": "O art. 26 da LINDB diz que a autoridade administrativa poderá celebrar compromisso após a oitiva do órgão jurídico e, 'quando for o caso', após realização de consulta pública. A consulta pública não é um requisito universal e obrigatório para todos os compromissos, dependendo da natureza, relevância e complexidade do objeto do acordo. A exigência de consulta pública deve ser avaliada caso a caso pela autoridade, à luz da conveniência e do interesse público.",
    "lei": "Art. 26. [...] a autoridade administrativa poderá, após oitiva do órgão jurídico e, quando for o caso, após realização de consulta pública, e presentes razões de relevante interesse geral, celebrar compromisso com os interessados.",
    "jurisprudencia": "A jurisprudência sobre o art. 26 enfatiza que o controle da legalidade dos acordos foca na transparência e no respeito ao interesse público. Não se exige um formalismo excessivo que impeça a celeridade administrativa. O que os órgãos de controle observam é se houve a oitiva do órgão jurídico, pois essa é a garantia fundamental para que a administração pública não firme compromissos ilegais que comprometam o patrimônio público.",
  },
  {
    "id": 29,
    "enunciado": "O direito à indenização por erro do Poder Judiciário, fundamentado em condenação indevida, obedece à lei do país onde o processo tramitou, não sendo possível invocar a LINDB para pleitear indenização por ato ocorrido no Brasil por estrangeiro.",
    "gabarito": "Errado",
    "justificativa": "A LINDB, em seu art. 7º, não obsta que estrangeiros pleiteiem indenizações em processos que tramitaram no Brasil. O direito à reparação de danos é regido, quanto aos fatos, pela lei do local do ato (lex loci delicti commissi), conforme art. 9º da LINDB. Se o ato ilícito (erro judicial ou dano) ocorreu em solo brasileiro, a lei aplicável à responsabilidade civil é a brasileira, independentemente da nacionalidade das partes envolvidas.",
    "lei": "Art. 9º Para qualificar e reger as obrigações, aplicar-se-á a lei do país em que se constituírem.",
    "jurisprudencia": "O STJ consolidou que o acesso à justiça e o direito à reparação de danos não podem ser negados a estrangeiros, desde que preenchidos os requisitos processuais. A jurisprudência trata a responsabilidade civil por atos praticados no Brasil sob o domínio da lei brasileira, o que garante a igualdade de tratamento em juízo, em observância ao artigo 5º da Constituição Federal, que garante a todos os que estão no território nacional o direito à proteção jurídica.",
  },
  {
    "id": 30,
    "enunciado": "Os atos administrativos praticados por autoridade competente, mesmo quando eivados de vícios formais, gozam de presunção de legitimidade absoluta, sendo vedada a anulação por controle judicial.",
    "gabarito": "Errado",
    "justificativa": "A presunção de legitimidade dos atos administrativos é **relativa** (juris tantum) e não absoluta. A LINDB, no art. 20 e 21, reforça que a invalidação de atos é perfeitamente possível e esperada quando constatada a ilegalidade. O que a nova legislação introduziu foram balizas para que essa anulação não seja desproporcional ou prejudicial ao interesse público, mas em nenhum momento retirou do Poder Judiciário ou da própria Administração o poder-dever de anular atos ilegais.",
    "lei": "Art. 21. A decisão que decretar a invalidação de ato, contrato, ajuste, processo ou norma administrativa deverá indicar de modo expresso as consequências jurídicas e administrativas da decisão.",
    "jurisprudencia": "O STF e o STJ mantêm o entendimento histórico de que a administração pública pode (e deve) anular seus próprios atos quando eivados de vícios de ilegalidade (Súmula 473 do STF). A mudança trazida pela Lei 13.655/2018 apenas impõe que esse poder de anulação não seja exercido de forma irresponsável, exigindo a análise das consequências. A jurisprudência agora foca no binômio 'legalidade vs. segurança jurídica' para decidir se o ato deve ser anulado ou apenas corrigido.",
  },
  {
    "id": 31,
    "enunciado": "A LINDB estabelece que, para o reconhecimento de filhos adotivos, será aplicada a lei do domicílio do adotado no momento da formalização do pedido de adoção.",
    "gabarito": "Errado",
    "justificativa": "O § 5º do art. 7º da LINDB é claro ao determinar que o reconhecimento de filho adotivo é regido pela lei do domicílio do **adotante**, e não do adotado. A lógica é que o adotante traz o adotado para o seu núcleo familiar e para a sua esfera de jurisdição, sendo o estatuto jurídico do adotante aquele que melhor define as condições e os direitos decorrentes da relação adotiva no ordenamento internacional.",
    "lei": "Art. 7º, § 5º O reconhecimento de filho adotivo, para fins de adoção, será regido pela lei do domicílio do adotante.",
    "jurisprudencia": "A jurisprudência do STJ, ao homologar sentenças estrangeiras de adoção, tem aplicado o critério do domicílio do adotante para definir a lei aplicável aos requisitos formais da adoção. Entende-se que, ao seguir a lei do adotante, evita-se o 'shopping forum', onde o interessado buscaria leis mais permissivas de outros países para contornar exigências do seu próprio domicílio.",
  },
  {
    "id": 32,
    "enunciado": "A inobservância da obrigatoriedade da oitiva do órgão jurídico, em casos de celebração de compromissos administrativos, pode levar à invalidade do ajuste firmado.",
    "gabarito": "Certo",
    "justificativa": "A oitiva do órgão jurídico, prevista no art. 26 da LINDB, é um requisito procedimental indispensável para a validade do compromisso administrativo. Esse parecer jurídico serve para assegurar que o acordo não viole a legalidade ou comprometa o patrimônio público. A ausência de manifestação técnica prévia configura vício formal grave, que pode ser suscitado pelos órgãos de controle para anular o ato.",
    "lei": "Art. 26. [...] a autoridade administrativa poderá, após oitiva do órgão jurídico e, quando for o caso, após realização de consulta pública [...] celebrar compromisso com os interessados.",
    "jurisprudencia": "Os tribunais de contas possuem jurisprudência consolidada no sentido de que atos de gestão pública que prescindem da análise jurídica prévia, quando exigida por lei, são nulos. No caso dos acordos da LINDB, o parecer jurídico é a salvaguarda da autoridade administrativa contra a imputação de dolo ou erro grosseiro posterior, configurando requisito de validade para o pacto firmado.",
  },
  {
    "id": 33,
    "enunciado": "Considera-se direito adquirido aquele cujo exercício tenha termo pré-fixado ou condição pré-estabelecida inalterável, a arbítrio de outrem.",
    "gabarito": "Errado",
    "justificativa": "A assertiva inverte o disposto no § 2º do art. 6º da LINDB. O texto legal afirma que são direitos adquiridos aqueles cujo exercício tenha condição pré-estabelecida inalterável, **a arbítrio de outrem (NÃO)**. Na verdade, a condição não pode depender da vontade alheia para ser considerada direito adquirido. A autonomia ou a certeza do direito é o que o torna incorporado ao patrimônio do titular.",
    "lei": "Art. 6º, § 2º Consideram-se adquiridos assim os direitos que o seu titular, ou alguém por ele, possa exercer, como aqueles cujo começo do exercício tenha termo pré-fixado, ou condição pré-estabelecida inalterável, a arbítrio de outrem (NEGADO PELA LEI).",
    "jurisprudencia": "A jurisprudência brasileira esclarece que o direito adquirido não se confunde com a simples expectativa de direito. Se o exercício do direito depende de um evento futuro incerto ou do arbítrio de terceiros, não há direito adquirido, mas mera expectativa. A proteção do art. 6º da LINDB atinge apenas aqueles direitos cujos requisitos já foram preenchidos ou cuja exigibilidade não mais depende de uma nova condição suspensiva.",
  },
  {
    "id": 34,
    "enunciado": "Para fins de aplicação da LINDB, as normas de Direito Público podem ser interpretadas levando em conta as exigências das políticas públicas a cargo do gestor.",
    "gabarito": "Certo",
    "justificativa": "O art. 22 da LINDB permite expressamente que, na interpretação das normas de gestão pública, o intérprete leve em consideração as exigências das políticas públicas. Isso é um reconhecimento de que o Direito não pode atuar de forma descolada da realidade administrativa e das necessidades de implementação de direitos sociais, contanto que essa interpretação não sacrifique os direitos fundamentais dos administrados.",
    "lei": "Art. 22. Na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor e as exigências das políticas públicas a seu cargo, sem prejuízo dos direitos dos administrados.",
    "jurisprudencia": "A jurisprudência tem aplicado este dispositivo para mitigar a responsabilidade de gestores em situações de escassez orçamentária. Entende-se que as políticas públicas possuem metas e cronogramas que devem ser respeitados, e o Poder Judiciário não deve interferir na priorização dessas políticas sem uma análise técnica robusta do impacto orçamentário, em respeito à discricionariedade técnica do gestor.",
  },
  {
    "id": 35,
    "enunciado": "A lei que começa a vigorar em todo o país após 45 dias de sua publicação é contada incluindo o dia da publicação e o dia da entrada em vigor.",
    "gabarito": "Errado",
    "justificativa": "A contagem dos prazos de vacatio legis obedece ao princípio de que se exclui o dia do começo e se inclui o dia do vencimento. Portanto, não se conta o dia da publicação. Essa é a regra geral do direito processual e administrativo para contagem de prazos em dias, garantindo que o período de 45 dias seja um intervalo completo e não truncado pela contagem do dia inicial.",
    "lei": "Art. 1º Salvo disposição contrária, a lei começa a vigorar em todo o país 45 (quarenta e cinco) dias depois de oficialmente publicada.",
    "jurisprudencia": "A jurisprudência do STJ corrobora a regra de que, na contagem de prazos, exclui-se o dia do início. No caso da vacatio legis, essa interpretação assegura que o objetivo do legislador (proporcionar tempo para o conhecimento da norma) seja efetivamente alcançado, evitando que a contagem do dia da publicação (que muitas vezes ocorre no final do expediente) reduza o tempo de adaptação da sociedade.",
  },
  {
    "id": 36,
    "enunciado": "O agente público somente responderá pessoalmente por suas decisões se comprovado o dolo, não sendo admitida a responsabilização por erro grosseiro, mesmo que este cause prejuízo ao erário.",
    "gabarito": "Errado",
    "justificativa": "O art. 28 da LINDB estabelece a responsabilidade pessoal em caso de dolo **ou** erro grosseiro. A alternativa está errada ao excluir o erro grosseiro. O legislador incluiu o erro grosseiro justamente para punir a negligência extrema, a imperícia flagrante ou a imprudência temerária na gestão pública, protegendo apenas o erro aceitável ou a interpretação razoável da lei.",
    "lei": "Art. 28. O agente público responderá pessoalmente por suas decisões ou opiniões técnicas em caso de dolo ou erro grosseiro.",
    "jurisprudencia": "O TCU definiu que o erro grosseiro é aquele que qualquer pessoa com nível médio de prudência ou conhecimento técnico evitaria. Assim, a jurisprudência atual não protege o gestor que atua com total desleixo no cumprimento de normas elementares de fiscalização, ainda que não haja prova de má-fé (dolo). O 'erro grosseiro' é, na prática, a negligência qualificada.",
  },
  {
    "id": 37,
    "enunciado": "Os atos de governo de país estrangeiro são sempre reconhecidos no Brasil, sem qualquer necessidade de verificação de compatibilidade com a ordem pública nacional.",
    "gabarito": "Errado",
    "justificativa": "O art. 17 da LINDB impõe uma barreira de proteção: a ordem pública. Qualquer ato ou lei estrangeira que fira a soberania nacional, a ordem pública ou os bons costumes não terá eficácia no Brasil. A ideia de que o reconhecimento é automático e irrestrito contraria o princípio da soberania nacional, que exige que o Direito Brasileiro preserve sua integridade ética e constitucional.",
    "lei": "Art. 17. As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil, quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "jurisprudencia": "A jurisprudência do STJ é enfática: o controle de ordem pública é prévio e obrigatório. Em pedidos de homologação de sentenças estrangeiras, o tribunal sempre analisa se a decisão não viola os direitos fundamentais garantidos pela Constituição de 1988. Se houver ofensa à ordem pública, a homologação é indeferida, mantendo o ato estrangeiro ineficaz no país.",
  },
  {
    "id": 38,
    "enunciado": "Na sucessão por morte de estrangeiro com bens situados no Brasil, a lei brasileira será aplicada, obrigatoriamente, em detrimento da lei do país de domicílio do falecido.",
    "gabarito": "Errado",
    "justificativa": "A regra geral (Art. 10) é que a sucessão obedece à lei do país onde o falecido era domiciliado. A aplicação da lei brasileira é excepcional (Art. 10, § 1º) e apenas se for mais favorável aos filhos ou cônjuge brasileiros, ou se o falecido não deixar herdeiros no país de domicílio. Portanto, não é uma aplicação obrigatória e irrestrita, mas sim facultativa e protetiva.",
    "lei": "Art. 10. A sucessão por morte ou por ausência obedece à lei do país em que domiciliado o defunto ou o desaparecido, qualquer que seja a natureza e a situação dos bens. § 1º A sucessão de bens de estrangeiros, situados no País, será regulada pela lei brasileira em benefício do cônjuge ou dos filhos brasileiros, ou de quem os represente, sempre que não lhes seja mais favorável a lei pessoal do de cujus.",
    "jurisprudencia": "Os tribunais entendem que essa proteção visa evitar que herdeiros nacionais brasileiros fiquem desamparados devido a regimes sucessórios estrangeiros menos protetivos. A jurisprudência avalia o conteúdo da lei estrangeira e da brasileira para verificar qual delas confere a maior quota-parte ou proteção aos sucessores brasileiros, respeitando o princípio da dignidade da pessoa humana.",
  },
  {
    "id": 39,
    "enunciado": "A decisão administrativa ou judicial que estabelecer nova orientação sobre norma de conteúdo indeterminado não precisa prever regime de transição se a mudança for motivada por jurisprudência superveniente do STF.",
    "gabarito": "Errado",
    "justificativa": "O art. 23 da LINDB não abre exceção para o fato de a mudança ser motivada por precedentes do STF. A obrigatoriedade do regime de transição é ditada pela necessidade de preservar a segurança jurídica e a confiança dos administrados. Se a mudança de orientação, mesmo que provocada pelo STF, impõe novos deveres ou condicionamentos que exigem adaptação, o regime de transição deve ser observado para que a mudança não seja arbitrária e danosa.",
    "lei": "Art. 23. A decisão administrativa, controladora ou judicial que estabelecer interpretação ou orientação nova sobre norma de conteúdo indeterminado [...] deverá prever regime de transição.",
    "jurisprudencia": "A jurisprudência do STF tem demonstrado preocupação com os efeitos ex tunc de suas decisões, utilizando frequentemente a técnica da modulação dos efeitos para cumprir o espírito do art. 23 da LINDB. Mesmo o STF reconhece que mudanças de paradigma devem ser graduais quando impactam severamente a segurança jurídica, aplicando prazos de adequação ou mantendo a vigência da interpretação anterior por um período determinado.",
  },
  {
    "id": 40,
    "enunciado": "A autoridade pública tem o dever de indicar, na invalidação de ato administrativo, as condições para a regularização proporcional, sendo vedado que tal regularização imponha ônus excessivos aos atingidos.",
    "gabarito": "Certo",
    "justificativa": "Este enunciado reflete a literalidade do parágrafo único do art. 21 da LINDB. A norma visa impedir que a administração, ao tentar corrigir um erro (anular o ato), cometa outro erro: punir os administrados de forma desproporcional. A transição deve ser equânime e evitar prejuízos excessivos aos sujeitos que, muitas vezes, confiaram na validade do ato agora invalidado.",
    "lei": "Art. 21, Parágrafo único. A decisão a que se refere o caput deste artigo deverá, quando for o caso, indicar as condições para que a nova regularização ocorra de modo proporcional e equânime e sem prejuízo aos interesses gerais, não se podendo impor aos sujeitos atingidos ônus ou perdas que, em função das peculiaridades do caso, sejam excessivos ou anormais.",
    "jurisprudencia": "A jurisprudência administrativa reforça o princípio da proteção da confiança legítima. Quando o Poder Público anula um ato, deve salvaguardar os direitos de terceiros de boa-fé. O tribunal de contas frequentemente determina que, em caso de anulação de contratos, a administração deve indenizar os serviços efetivamente prestados e os custos incorridos, sob pena de enriquecimento ilícito do Estado, conforme determina o art. 21 da LINDB.",
  },
  {
    "id": 41,
    "enunciado": "A qualificação dos bens é regida pela lei do país em que estiverem situados, inclusive quanto aos bens móveis que o proprietário trouxer consigo para o Brasil.",
    "gabarito": "Certo",
    "justificativa": "O art. 8º da LINDB estabelece que a lei do país em que se situarem os bens rege a qualificação e os direitos a eles concernentes. No caso dos bens móveis, aplica-se a regra de que o bem segue o local onde se encontra (lex rei sitae). Mesmo bens móveis trazidos pelo proprietário, ao entrarem no território brasileiro, passam a ser regidos pela lei brasileira no que tange à sua natureza, posse e direitos reais, salvo disposição contrária em tratados.",
    "lei": "Art. 8º Para qualificar os bens e regular as relações a eles concernentes, aplicar-se-á a lei do país em que estiverem situados.",
    "jurisprudencia": "A jurisprudência do STJ confirma que a lex rei sitae é o critério de conexão mais seguro para conflitos de direitos reais. Independentemente de onde o bem foi adquirido ou de quem é o proprietário, a lei do local onde o bem se encontra rege as questões de posse, propriedade e gravames, garantindo que o direito local tenha soberania sobre os objetos situados em seu território, facilitando a execução de medidas judiciais e o registro público.",
  },
  {
    "id": 42,
    "enunciado": "A LINDB determina que, se o cônjuge brasileiro for prejudicado por lei estrangeira, poderá pleitear a aplicação da lei brasileira para regular o seu regime de bens, independentemente do domicílio do casal.",
    "gabarito": "Errado",
    "justificativa": "A LINDB, em seu art. 7º, § 4º, estipula que o regime de bens, legal ou convencional, obedece à lei do país em que tiverem os nubentes domicílio. Se o domicílio for o Brasil, aplica-se a lei brasileira. Se for no estrangeiro, aplica-se a lei local. A lei não concede ao cônjuge a faculdade de 'escolher' a lei brasileira apenas por ser esta mais favorável, a menos que o domicílio conjugal seja no Brasil ou haja previsão expressa em convenção antenupcial.",
    "lei": "Art. 7º, § 4º O regime de bens, legal ou convencional, obedece à lei do país em que tiverem os nubentes domicílio, e, se este for diverso, à do primeiro domicílio conjugal.",
    "jurisprudencia": "O STJ tem adotado uma interpretação rigorosa do critério de conexão domiciliar para evitar que os nubentes burlem o regime de bens aplicável ao seu domicílio real. A jurisprudência entende que a autonomia da vontade no Direito de Família é limitada pelas normas de ordem pública, e a lei do domicílio é o ponto de conexão que confere previsibilidade e estabilidade às relações patrimoniais do casal.",
  },
  {
    "id": 43,
    "enunciado": "A autoridade administrativa poderá celebrar compromisso com interessados para eliminar incerteza jurídica, mas tal compromisso não possui força vinculante para as futuras administrações.",
    "gabarito": "Errado",
    "justificativa": "O compromisso celebrado nos moldes do art. 26 da LINDB possui força vinculante para a administração que o assinou. A ideia do legislador ao introduzir este instituto é exatamente criar um ambiente de segurança jurídica onde os termos pactuados sejam respeitados, evitando que o administrado seja surpreendido por mudanças unilaterais de entendimento sem causa superveniente justificada. Ele integra o patrimônio jurídico do acordo e, salvo vício, deve ser cumprido.",
    "lei": "Art. 26. [...] a autoridade administrativa poderá [...] celebrar compromisso com os interessados.",
    "jurisprudencia": "A jurisprudência sobre atos administrativos consensuais indica que o princípio da boa-fé objetiva veda o comportamento contraditório (venire contra factum proprium) da administração. Uma vez celebrado um compromisso na forma da lei, a administração pública não pode rescindi-lo unilateralmente sem motivação idônea, sob pena de responder pelos prejuízos causados ao particular que confiou na estabilidade daquele ajuste.",
  },
  {
    "id": 44,
    "enunciado": "Para a aplicação do art. 20 da LINDB, o julgador deve demonstrar a adequação da medida imposta, inclusive comparando-a com as possíveis alternativas menos gravosas.",
    "gabarito": "Certo",
    "justificativa": "O parágrafo único do art. 20 da LINDB impõe ao julgador o dever de motivar a decisão comparando a medida com outras possíveis alternativas. Isso faz parte da 'análise consequencialista'. Não basta dizer que a medida é boa; é necessário demonstrar que, diante das alternativas, aquela foi a escolhida por ser a mais eficiente e menos onerosa, cumprindo o princípio da proporcionalidade em sentido amplo.",
    "lei": "Art. 20, Parágrafo único. A motivação demonstrará a necessidade e a adequação da medida imposta ou da invalidação de ato, contrato, ajuste, processo ou norma administrativa, inclusive em face das possíveis alternativas.",
    "jurisprudencia": "O TCU tem anulado decisões de seus próprios processos internos ou de gestores que não apresentaram essa análise comparativa de alternativas. A jurisprudência entende que a ausência dessa comparação torna a decisão 'abstrata' e, portanto, em desacordo com o novo paradigma da LINDB. A exigência de demonstrar que não havia alternativa menos danosa é a materialização do dever de eficiência no processo administrativo.",
  },
  {
    "id": 45,
    "enunciado": "A LINDB não admite o casamento celebrado no estrangeiro por brasileiro se não houver o registro do respectivo assento em consulado brasileiro ou em cartório do 1º Ofício no Brasil.",
    "gabarito": "Errado",
    "justificativa": "O casamento é regido pela lei do local de sua celebração (lex loci celebrationis), conforme art. 7º, § 1º. A validade do casamento não depende do registro consular ou em cartório brasileiro para sua existência no plano do direito internacional; o registro tem caráter declaratório e de publicidade para produção de efeitos plenos no Brasil, mas a inexistência deste não retira a validade do ato perante o direito das gentes.",
    "lei": "Art. 7º, § 1º Realizado o casamento no estrangeiro, perante as autoridades deste, e obedecidos os requisitos de forma ali exigidos, terá validade no Brasil.",
    "jurisprudencia": "O entendimento consolidado é que a lei do local da celebração é suficiente para a validade formal. A jurisprudência reconhece que a exigência de transcrição (registro) no Brasil é apenas uma formalidade para que o casamento seja reconhecido pelo sistema de registro civil brasileiro e produza efeitos sucessórios ou de nacionalidade de forma célere, mas a falta do registro não implica a nulidade absoluta do vínculo matrimonial.",
  },
  {
    "id": 46,
    "enunciado": "O erro grosseiro de agente público, para fins de responsabilização pessoal, é aquele que resulta de uma interpretação razoável da lei, desde que resulte em prejuízo ao erário.",
    "gabarito": "Errado",
    "justificativa": "A LINDB exclui explicitamente a responsabilidade por 'interpretação razoável'. O art. 28 visa punir apenas dolo ou erro grosseiro. Se a interpretação é razoável, ainda que no futuro venha a ser considerada incorreta pelos órgãos de controle, ela não configura erro grosseiro e, portanto, não gera responsabilidade pessoal do agente. A interpretação razoável é um porto seguro para o gestor proativo.",
    "lei": "Art. 28. O agente público responderá pessoalmente por suas decisões ou opiniões técnicas em caso de dolo ou erro grosseiro.",
    "jurisprudencia": "A jurisprudência do STF e do TCU protege o gestor que atua em zonas de penumbra normativa. Se havia margem para interpretação e o gestor escolheu uma delas de maneira fundamentada, não há como cogitar responsabilidade. O erro grosseiro deve ser um erro que qualquer observador médio classificaria como inescusável, desprovido de qualquer razoabilidade jurídica ou técnica.",
  },
  {
    "id": 47,
    "enunciado": "A lei estrangeira, mesmo quando não ofende a ordem pública, não terá eficácia no Brasil se não houver reciprocidade diplomática entre os dois países.",
    "gabarito": "Errado",
    "justificativa": "A LINDB não exige reciprocidade diplomática para a eficácia das leis estrangeiras (ressalvados casos específicos de tratados internacionais ou homologação de sentenças). A aplicação da lei estrangeira (como a do local da constituição de uma obrigação) é uma determinação do próprio direito brasileiro (LINDB). O Brasil aplica a lei estrangeira porque seu sistema de Direito Internacional Privado assim o determina, não por uma troca de favores entre estados.",
    "lei": "Art. 9º Para qualificar e reger as obrigações, aplicar-se-á a lei do país em que se constituírem.",
    "jurisprudencia": "A jurisprudência indica que a aplicação de lei estrangeira é um dever do juiz brasileiro (iura novit curia internacional), sempre que o sistema de conexão o indique. Não se trata de cortesia internacional ou necessidade de tratados de reciprocidade, mas de uma norma de aplicação do nosso próprio sistema jurídico para a resolução de conflitos de leis no espaço.",
  },
  {
    "id": 48,
    "enunciado": "O conceito de 'bons costumes', presente na LINDB, deve ser interpretado como a moralidade média da sociedade local, podendo ser utilizado para negar eficácia a declarações de vontade estrangeiras.",
    "gabarito": "Certo",
    "justificativa": "Os 'bons costumes', juntamente com a 'ordem pública' e a 'soberania nacional', formam a tríade de limites à aplicação do direito estrangeiro no Brasil (Art. 17). Esse conceito evolui com o tempo e com a sociedade. O magistrado brasileiro tem o poder de avaliar se uma declaração de vontade ou ato estrangeiro afronta o padrão ético mínimo admitido no Brasil para que o ato seja tutelado pelo nosso sistema judiciário.",
    "lei": "Art. 17. As leis, atos e sentenças de outro país, bem como quaisquer declarações de vontade, não terão eficácia no Brasil, quando ofenderem a soberania nacional, a ordem pública e os bons costumes.",
    "jurisprudencia": "Embora a expressão 'bons costumes' possa parecer subjetiva, a jurisprudência a interpreta como os princípios éticos da Constituição, como a vedação ao lucro desmedido sobre a exploração humana ou práticas contrárias à dignidade. É um conceito de preenchimento valorativo pelo magistrado, sempre sob a luz dos direitos fundamentais, impedindo que o Direito Brasileiro chancelasse práticas tidas como repugnantes pela nossa sociedade.",
  },
  {
    "id": 49,
    "enunciado": "A vacatio legis de 45 dias pode ser ampliada ou reduzida pelo juiz em casos de urgência social, para garantir a efetividade da lei.",
    "gabarito": "Errado",
    "justificativa": "O prazo de 45 dias da vacatio legis é estabelecido por norma legal (Art. 1º). O magistrado não possui competência legislativa para ampliar ou reduzir prazos de entrada em vigor de leis, sob pena de violação ao princípio da separação dos poderes. A vacatio legis é um período que cabe ao legislador definir; se a lei não o define, aplica-se o prazo legal, não havendo discricionariedade judicial para alterá-lo.",
    "lei": "Art. 1º Salvo disposição contrária, a lei começa a vigorar em todo o país 45 (quarenta e cinco) dias depois de oficialmente publicada.",
    "jurisprudencia": "A jurisprudência brasileira é pacífica quanto à impossibilidade de o Judiciário modificar prazos de vigência de leis. O Poder Judiciário aplica a lei, não a cria. Qualquer intervenção judicial para alterar o prazo de vacância seria uma usurpação da função legislativa, ferindo a segurança jurídica, pois a lei deve ter vigência uniforme para todos os cidadãos, sem variações baseadas em decisões judiciais fragmentadas.",
  },
  {
    "id": 50,
    "enunciado": "Ao julgar casos envolvendo a gestão pública, o magistrado deve desconsiderar as dificuldades reais do gestor se houver risco de dano ao erário, pois a proteção ao patrimônio público é absoluta.",
    "gabarito": "Errado",
    "justificativa": "O art. 22 da LINDB diz expressamente o contrário: na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor. O Direito não exige resultados impossíveis. O risco de dano ao erário é um fator a ser considerado, mas não elimina o dever do julgador de ponderar as dificuldades contextuais enfrentadas pelo gestor na sua atuação proativa.",
    "lei": "Art. 22. Na interpretação de normas sobre gestão pública, serão considerados os obstáculos e as dificuldades reais do gestor e as exigências das políticas públicas a seu cargo, sem prejuízo dos direitos dos administrados.",
    "jurisprudencia": "A jurisprudência mais moderna, especialmente sob a ótica do Direito Administrativo da Nova LINDB, afasta o controle punitivo baseado em expectativas irreais. Tribunais de Contas e juízes têm considerado que o dever de zelar pelo erário não pode impedir a gestão eficiente, e que a interpretação da norma deve ser contextualizada. O dano ao erário precisa ser concreto, não apenas uma consequência de escolhas difíceis tomadas dentro da margem de discricionariedade do gestor.",
  },
  {
    "id": 51,
    "enunciado": "A LINDB veda que a decisão judicial fundamente a anulação de um contrato administrativo apenas em valores jurídicos abstratos, sem demonstrar que a alternativa de anulação é a menos lesiva ao interesse público.",
    "gabarito": "Certo",
    "justificativa": "O art. 20 em conjunto com o parágrafo único do mesmo artigo, ambos da LINDB, impõe que toda invalidação de contrato administrativo seja acompanhada de uma análise concreta das consequências práticas. O julgador não pode apenas dizer que o contrato é 'imoral' ou 'ilegal'; ele deve demonstrar que a anulação é a medida que melhor atende ao interesse público, comparando-a com as alternativas, como a manutenção do contrato com glosas ou a repactuação.",
    "lei": "Art. 20, Parágrafo único. A motivação demonstrará a necessidade e a adequação da medida imposta ou da invalidação de ato, contrato, ajuste, processo ou norma administrativa, inclusive em face das possíveis alternativas.",
    "jurisprudencia": "A jurisprudência do TCU e do STJ é clara: a anulação de contratos deve ser a 'ultima ratio'. Quando a irregularidade for sanável, o interesse público é melhor preservado pela manutenção do contrato do que pela sua anulação abrupta, que interromperia serviços essenciais e geraria custos de nova licitação. A decisão judicial ou administrativa que ignora esse dever de motivação consequencialista é nula por vício de fundamentação.",
  },
  {
    "id": 52,
    "enunciado": "O domicílio da pessoa, para fins de aplicação da lei pessoal, é o local onde ela estabelece sua residência habitual, independentemente de qualquer intenção de ali se fixar permanentemente.",
    "gabarito": "Errado",
    "justificativa": "O domicílio, segundo a definição do Código Civil (norma interpretativa para a LINDB), não é apenas a residência habitual, mas o local onde a pessoa estabelece sua residência com a intenção de ali permanecer. Portanto, a intenção (animus manendi) é elemento constitutivo do domicílio. A LINDB utiliza o critério do domicílio para definir a lei pessoal justamente porque ele representa um vínculo mais estável do que a mera residência.",
    "lei": "Art. 7º A lei do país em que domiciliada a pessoa determina as regras sobre o começo e o fim da personalidade, o nome, a capacidade e os direitos de família.",
    "jurisprudencia": "A jurisprudência sobre o conceito de domicílio para fins de Direito Internacional Privado é rigorosa. O STJ entende que a simples passagem ou estadia prolongada sem intenção de fixação (como em viagens de turismo ou estudos temporários) não desloca o domicílio para fins de aplicação da lei pessoal. O domicílio é um conceito jurídico que exige prova do vínculo real com a comunidade onde a pessoa se encontra.",
  },
  {
    "id": 53,
    "enunciado": "A proibição de que o magistrado decida com base em valores jurídicos abstratos aplica-se apenas ao Poder Judiciário, não atingindo os órgãos de controle interno da Administração Pública.",
    "gabarito": "Errado",
    "justificativa": "O art. 20 da LINDB menciona expressamente as três esferas: administrativa, controladora e judicial. Portanto, os órgãos de controle, como Controladoria-Geral, Tribunais de Contas e auditorias internas, estão igualmente submetidos ao dever de fundamentar suas decisões com base nas consequências práticas e não apenas em abstrações como 'interesse público' ou 'boa governança' sem lastro fático.",
    "lei": "Art. 20. Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão.",
    "jurisprudencia": "Os Tribunais de Contas têm adaptado seus manuais e normativos internos para refletir a nova LINDB. A jurisprudência dos tribunais superiores reafirma que o 'direito administrativo do medo', fruto de uma atuação dos órgãos de controle baseada em generalidades, é incompatível com o sistema jurídico vigente pós-Lei 13.655/2018.",
  },
  {
    "id": 54,
    "enunciado": "Para a validade da prova de fatos ocorridos no exterior, o documento deve conter selo de autenticidade emitido pelo Itamaraty, sendo a única forma de prova admitida em juízo.",
    "gabarito": "Errado",
    "justificativa": "A LINDB (Art. 13) exige que a prova siga os meios admitidos pela lei brasileira e que o fato seja provado de acordo com a lei do local. Não existe uma 'única forma' de prova, como apenas o selo do Itamaraty. Com a ratificação da Convenção da Apostila de Haia, o procedimento de legalização documental foi simplificado, e o Direito brasileiro aceita diversos meios de prova documental, desde que respeitados os tratados e o contraditório.",
    "lei": "Art. 13. A prova dos fatos ocorridos em país estrangeiro rege-se pela lei que nele vigorar, quanto ao ônus e aos meios de produzir-se, não admitindo os tribunais brasileiros provas que a lei brasileira desconheça.",
    "jurisprudencia": "A jurisprudência atual dá prioridade à cooperação internacional. O STJ entende que, na ausência de tratado específico, a prova deve passar por conferência mínima, mas o juiz não deve ser excessivamente formalista ao ponto de impedir o acesso à justiça se a prova for idônea e o fato puder ser confirmado por outros meios, respeitando o princípio da busca pela verdade real.",
  },
  {
    "id": 55,
    "enunciado": "A alteração de jurisprudência do STF sobre norma de conteúdo indeterminado não obriga a previsão de regime de transição se a decisão for proferida em sede de controle concentrado.",
    "gabarito": "Errado",
    "justificativa": "A LINDB não diferencia a origem da decisão. Tanto decisões em controle concentrado (como ADIs) quanto em outras instâncias devem observar o regime de transição (Art. 23) caso estabeleçam nova orientação sobre norma de conteúdo indeterminado que impacte a segurança jurídica. O STF, aliás, tem utilizado a modulação de efeitos para atender exatamente a esse preceito da LINDB.",
    "lei": "Art. 23. A decisão administrativa, controladora ou judicial que estabelecer interpretação ou orientação nova sobre norma de conteúdo indeterminado [...] deverá prever regime de transição.",
    "jurisprudencia": "O STF tem reconhecido que, embora possua competência para modular os efeitos, o dever de fazê-lo é imposto pela necessidade de evitar prejuízos a quem agiu conforme o entendimento anterior. A jurisprudência constitucional recente é sensível a essa necessidade de transição para que a mudança de entendimento não destrua direitos consolidados pela interpretação que o próprio Supremo antes mantinha.",
  },
  {
    "id": 56,
    "enunciado": "O dolo, para fins de responsabilização do agente público segundo a LINDB, deve ser entendido como a vontade livre e consciente de alcançar o resultado ilícito.",
    "gabarito": "Certo",
    "justificativa": "No Direito Administrativo sancionador e sob a ótica da LINDB, o dolo exige a presença do elemento volitivo (vontade). Não basta que o agente tenha agido de forma a causar dano; é necessário que ele tenha buscado o resultado ou assumido o risco de produzi-lo de forma consciente (dolo eventual), diferenciando-o da culpa (negligência, imprudência ou imperícia).",
    "lei": "Art. 28. O agente público responderá pessoalmente por suas decisões ou opiniões técnicas em caso de dolo ou erro grosseiro.",
    "jurisprudencia": "A jurisprudência administrativa define dolo como o elemento subjetivo do tipo que qualifica a conduta como antijurídica. Se o agente agiu com a intenção de beneficiar terceiros ou a si próprio em detrimento do interesse público, o dolo é evidente. Já na ausência de intenção, a responsabilização só é possível se ficar configurado que o descuido foi tão grave que se equipara à má-fé (o erro grosseiro).",
  },
  {
    "id": 57,
    "enunciado": "A LINDB autoriza que a autoridade administrativa, ao celebrar um compromisso, dispense a oitiva do órgão jurídico se o valor do acordo for irrisório.",
    "gabarito": "Errado",
    "justificativa": "O art. 26 da LINDB é taxativo quanto à necessidade de oitiva do órgão jurídico. A lei não criou uma exceção baseada no 'valor irrisório'. A oitiva jurídica é uma garantia técnica para que a autoridade pública não se comprometa em situações que possam ser ilegais ou prejudiciais ao erário, independentemente do montante financeiro envolvido. A dispensa de um requisito legal sem amparo na lei configura ilegalidade do ato.",
    "lei": "Art. 26. [...] a autoridade administrativa poderá, após oitiva do órgão jurídico e, quando for o caso, após realização de consulta pública [...] celebrar compromisso com os interessados.",
    "jurisprudencia": "A jurisprudência dos órgãos de controle é rigorosa quanto ao cumprimento das etapas procedimentais previstas em lei. A supressão de uma etapa de controle, mesmo que o valor seja pequeno, é vista como um perigoso precedente de enfraquecimento do controle administrativo, sendo, portanto, vedada pelos órgãos de fiscalização.",
  },
  {
    "id": 58,
    "enunciado": "O princípio da irretroatividade da lei, previsto na LINDB, não se aplica às leis interpretativas, que podem alcançar fatos passados para definir o sentido original da norma.",
    "gabarito": "Certo",
    "justificativa": "Embora a LINDB (Art. 6º) estabeleça o princípio da irretroatividade, a doutrina e a jurisprudência entendem que a lei interpretativa é uma exceção aparente. Ela não cria direito novo, apenas esclarece o sentido de uma norma que já existia. Como a interpretação acompanha o sentido da norma original, ela se aplica aos fatos passados que ainda não foram julgados, sem que isso configure retroatividade proibida.",
    "lei": "Art. 6º A Lei em vigor terá efeito imediato e geral, respeitados o ato jurídico perfeito, o direito adquirido e a coisa julgada.",
    "jurisprudencia": "O STF consolidou que as leis interpretativas têm eficácia retroativa, pois o legislador apenas declara o conteúdo que a norma sempre teve. Isso é diferente da lei nova que altera o Direito, que respeita o ato jurídico perfeito. A jurisprudência usa esse entendimento para evitar que interpretações divergentes prolonguem o tempo de incerteza sobre o alcance de normas legais.",
  },
  {
    "id": 59,
    "enunciado": "Para garantir a eficiência, o magistrado pode dispensar a análise de consequências práticas se a ação for uma medida de emergência sanitária.",
    "gabarito": "Errado",
    "justificativa": "A LINDB não autoriza exceção para casos de emergência sanitária. Pelo contrário, em situações de crise (como pandemias), a análise de consequências é ainda mais crucial, pois uma decisão errada pode causar o colapso do sistema de saúde. O Art. 20 é absoluto quanto à necessidade de fundamentação baseada nas consequências, especialmente em políticas públicas de alta relevância.",
    "lei": "Art. 20. Nas esferas administrativa, controladora e judicial, não se decidirá com base em valores jurídicos abstratos sem que sejam consideradas as consequências práticas da decisão.",
    "jurisprudencia": "A jurisprudência durante a pandemia de COVID-19 reforçou que o Poder Judiciário deve atuar em diálogo com os gestores de saúde, evitando decisões que ignorassem os dados técnicos de disponibilidade de leitos, oxigênio ou vacinas. A análise das consequências práticas demonstrou ser o único caminho viável para evitar decisões judiciais contraditórias e ineficazes.",
  },
  {
    "id": 60,
    "enunciado": "A LINDB possui natureza de norma de sobredireito, ou seja, é uma norma que dita como o próprio Direito deve ser aplicado, interpretado e integrado no sistema brasileiro.",
    "gabarito": "Certo",
    "justificativa": "A LINDB (Decreto-Lei 4.657/1942) é, por excelência, a norma fundamental de estruturação do sistema jurídico brasileiro. Ela não dita regras de comportamento (como o Código Penal ou o Código Civil), mas dita as regras de como as outras leis devem ser compreendidas, vigentes e integradas. É a lei de introdução de todo o ordenamento, funcionando como o 'código dos códigos' quanto aos métodos de aplicação do Direito.",
    "lei": "Art. 1º Salvo disposição contrária, a lei começa a vigorar em todo o país 45 (quarenta e cinco) dias depois de oficialmente publicada.",
    "jurisprudencia": "A jurisprudência trata a LINDB como uma norma de sobredireito de aplicação geral e obrigatória. Quando o STF decide sobre a validade de uma lei, ele se baseia nos conceitos de ato jurídico perfeito e direito adquirido da LINDB. Sem essa lei, o sistema jurídico brasileiro seria desorganizado, sem critérios claros para resolver os conflitos de normas no tempo e no espaço, o que seria insustentável.",
  }
];